spring:
  datasource:
    url: jdbc:h2:mem:credit_application_db
    username: admin

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
